-- MySQL Script generated by MySQL Workbench
-- jue 18 may 2017 22:30:27 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proy_final
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proy_final
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proy_final` DEFAULT CHARACTER SET utf8 ;
USE `proy_final` ;

-- -----------------------------------------------------
-- Table `proy_final`.`persona`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proy_final`.`persona` ;

CREATE TABLE IF NOT EXISTS `proy_final`.`persona` (
  `cpPersona` INT NOT NULL AUTO_INCREMENT,
  `apPaterno` VARCHAR(45) NULL,
  `apMaterno` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `fechaNacimiento` DATE NULL,
  PRIMARY KEY (`cpPersona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_final`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proy_final`.`usuario` ;

CREATE TABLE IF NOT EXISTS `proy_final`.`usuario` (
  `cpUsuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `cpPersona` INT NOT NULL,
  PRIMARY KEY (`cpUsuario`),
  INDEX `fk_usuario_persona1_idx` (`cpPersona` ASC),
  CONSTRAINT `fk_usuario_persona1`
    FOREIGN KEY (`cpPersona`)
    REFERENCES `proy_final`.`persona` (`cpPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_final`.`domicilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proy_final`.`domicilio` ;

CREATE TABLE IF NOT EXISTS `proy_final`.`domicilio` (
  `cpDomicilio` INT NOT NULL AUTO_INCREMENT,
  `calle` VARCHAR(45) NULL,
  `noInt` INT NULL,
  `noExt` VARCHAR(45) NULL,
  `colonia` VARCHAR(45) NULL,
  `municipio` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  PRIMARY KEY (`cpDomicilio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_final`.`medico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proy_final`.`medico` ;

CREATE TABLE IF NOT EXISTS `proy_final`.`medico` (
  `cpMedico` INT NOT NULL AUTO_INCREMENT,
  `costo` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `cpPersona` INT NOT NULL,
  `cpDomicilio` INT NOT NULL,
  PRIMARY KEY (`cpMedico`),
  INDEX `fk_medico_persona1_idx` (`cpPersona` ASC),
  INDEX `fk_medico_domicilio1_idx` (`cpDomicilio` ASC),
  CONSTRAINT `fk_medico_persona1`
    FOREIGN KEY (`cpPersona`)
    REFERENCES `proy_final`.`persona` (`cpPersona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_medico_domicilio1`
    FOREIGN KEY (`cpDomicilio`)
    REFERENCES `proy_final`.`domicilio` (`cpDomicilio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_final`.`disponibilidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proy_final`.`disponibilidad` ;

CREATE TABLE IF NOT EXISTS `proy_final`.`disponibilidad` (
  `cpDisponibilidad` INT NOT NULL AUTO_INCREMENT,
  `dia` VARCHAR(45) NULL,
  `horaInicio` TIME NULL,
  `horaFin` TIME NULL,
  `cpMedico` INT NOT NULL,
  PRIMARY KEY (`cpDisponibilidad`),
  INDEX `fk_disponibilidad_medico1_idx` (`cpMedico` ASC),
  CONSTRAINT `fk_disponibilidad_medico1`
    FOREIGN KEY (`cpMedico`)
    REFERENCES `proy_final`.`medico` (`cpMedico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `proy_final`.`cita`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proy_final`.`cita` ;

CREATE TABLE IF NOT EXISTS `proy_final`.`cita` (
  `cpCita` INT NOT NULL AUTO_INCREMENT,
  `cpUsuario` INT NOT NULL,
  `fechaHora` DATETIME NULL,
  PRIMARY KEY (`cpCita`),
  INDEX `fk_cita_usuario1_idx` (`cpUsuario` ASC),
  CONSTRAINT `fk_cita_usuario1`
    FOREIGN KEY (`cpUsuario`)
    REFERENCES `proy_final`.`usuario` (`cpUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
